export default {
  REQUEST_POSTS: "REQUEST_POSTS",
  REQUEST_POSTS_SUCCESS: "REQUEST_POSTS_SUCCESS",
  REQUEST_POSTS_FAILED: "REQUEST_POSTS_FAILED",

  ADD_POST: "ADD_POST",
  ADD_POST_FAILED: "ADD_POST_FAILED",

  UPDATE_POST: "UPDATE_POST",
  UPDATE_POST_FAILED: "UPDATE_POST_FAILED",

  DELETE_POST: "DELETE_POST",
  DELETE_POST_FAILED: "DELETE_POST_FAILED"
};
